version: '3'

tasks:
  bootstrap:
    desc: Provision a fresh Pi from scratch
    dir: deploy
    cmd: ansible-playbook bootstrap.yml

  deploy:
    desc: Deploy latest code to Pi
    dir: deploy
    cmd: ansible-playbook deploy.yml

  restore:
    desc: Restore event data from CSV backup
    dir: deploy
    cmd: >-
      ansible-playbook restore.yml
      {{if .FROSTBYTE_CSV}}-e frostbyte_csv={{.FROSTBYTE_CSV}}{{end}}
      {{if .LABELMAKER_CSV}}-e labelmaker_csv={{.LABELMAKER_CSV}}{{end}}

  migrate:
    desc: Run all migration scripts on the Pi
    dir: deploy
    cmd: ansible-playbook migrate.yml

  dev:
    desc: Start dev environment with hot reloading
    cmd: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

  dev:stop:
    desc: Stop dev environment
    cmd: docker compose -f docker-compose.yml -f docker-compose.dev.yml down
